# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import asyncio
import aiohttp
import os
import pytz
import base64
from datetime import datetime, date
from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message
from langbot_plugin.api.entities.builtin.provider import message as provider_message


class DefaultEventListener(EventListener):
    
    def __init__(self):
        super().__init__()
    
    async def initialize(self):
        await super().initialize()
        
        self.time_zone = self.plugin.get_config().get('time_zone', "Asia/Shanghai")
        self.api_token = self.plugin.get_config().get('api_token', '')
        @self.handler(events.PersonMessageReceived)
        @self.handler(events.GroupMessageReceived)
        async def handler(event_context: context.EventContext):
            # 获取消息内容
            message_chain = event_context.event.message_chain
            message = "".join(
                element.text for element in message_chain
                if isinstance(element, platform_message.Plain)
            ).strip()
            
            # 只处理"运势"关键词的消息
            if message != "运势":
                return
            
            # 获取用户ID
            user_id = str(event_context.event.sender_id)
            
            # 检查用户是否已经在今天请求过
            if await self.has_requested_today(user_id):
                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Plain(text="您今天已经查询过运势了，请明天再来吧！")
                    ])
                )
                event_context.prevent_default()
                return
            
            try:
                # 异步请求每日运势API，获取base64格式的图片
                horoscope_base64 = await self.fetch_horoscope_image()
                
                # 发送图片
                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Image(base64=horoscope_base64)
                    ])
                )
                
                # 记录用户请求
                await self.record_request(user_id)
                
            except Exception as e:
                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Plain(text=f"获取运势失败: {str(e)}")
                    ])
                )
            
            event_context.prevent_default()
    
    async def fetch_horoscope_image(self):
            """异步请求运势图片并转换为base64格式"""
            # 1. 纯净的 URL，不再携带 Token 
            url = "https://api.092399.xyz/api/yunshi/yunshi.php"
            
            # 2. 将 Token 放入请求头
            headers = {
                "X-Token": self.api_token
            }

            async with aiohttp.ClientSession() as session:
                # 3. 发起请求时带上 headers
                async with session.get(url, headers=headers, ssl=False) as response:
                    # 检查是否为 403 错误
                    if response.status == 403:
                        raise Exception("API Token无效或未配置，请检查插件配置中的api_token。")

                    response.raise_for_status()
                    # 读取图片数据
                    image_data = await response.read()
                    # 转换为 base64
                    img_base64 = base64.b64encode(image_data).decode('utf-8')
                    return img_base64
    
    async def has_requested_today(self, user_id):
        """检查用户今天是否已经请求过"""
        # 使用配置的时区获取今天的日期
        tz = pytz.timezone(self.time_zone)
        today = datetime.now(tz).strftime("%Y-%m-%d")
        
        try:
            # 使用插件数据持久化功能获取用户请求记录
            storage_key = f"user_request_{user_id}"
            stored_date_bytes = await self.plugin.get_plugin_storage(storage_key)
            
            if stored_date_bytes:
                # 将字节转换回字符串
                stored_date = stored_date_bytes.decode('utf-8')
                # 检查存储的日期是否为今天
                return stored_date == today
            
        except Exception as e:
            print(f"检查请求记录失败: {e}")
        
        return False
    
    async def record_request(self, user_id):
        """记录用户请求"""
        # 使用配置的时区获取今天的日期
        tz = pytz.timezone(self.time_zone)
        today = datetime.now(tz).strftime("%Y-%m-%d")
        
        try:
            # 使用插件数据持久化功能保存用户请求记录
            storage_key = f"user_request_{user_id}"
            # 将日期字符串转换为字节
            today_bytes = today.encode('utf-8')
            await self.plugin.set_plugin_storage(storage_key, today_bytes)
                
        except Exception as e:
            print(f"记录请求失败: {e}")