# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import asyncio
import aiohttp
import os
import pytz
from datetime import datetime, date
from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message
from langbot_plugin.api.entities.builtin.provider import message as provider_message


class DefaultEventListener(EventListener):
    
    def __init__(self):
        super().__init__()
    
    async def initialize(self):
        await super().initialize()
        
        self.time_zone = self.plugin.get_config().get('time_zone', "Asia/Shanghai")
        @self.handler(events.PersonMessageReceived)
        @self.handler(events.GroupMessageReceived)
        async def handler(event_context: context.EventContext):
            # 获取消息内容
            message_chain = event_context.event.message_chain
            message = "".join(
                element.text for element in message_chain
                if isinstance(element, platform_message.Plain)
            ).strip()
            
            # 只处理包含"运势"关键词的消息
            if "运势" not in message:
                return
            
            # 获取用户ID
            user_id = str(event_context.event.sender_id)
            launcher_type = event_context.event.launcher_type
            
            # 检查用户是否已经在今天请求过
            if await self.has_requested_today(user_id):
                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Plain(text="您今天已经查询过运势了，请明天再来！")
                    ])
                )
                event_context.prevent_default()
                return
            
            try:
                # 异步请求每日运势API
                horoscope_url = await self.fetch_horoscope_image()
                
                # 发送图片
                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Image(url=horoscope_url)
                    ])
                )
                
                # 记录用户请求
                await self.record_request(user_id)
                
            except Exception as e:
                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Plain(text=f"获取运势失败: {str(e)}")
                    ])
                )
            
            event_context.prevent_default()
    
    async def fetch_horoscope_image(self):
        """异步请求运势图片（API直接返回图片数据）"""
        url = "https://www.hhlqilongzhu.cn/api/tu_yunshi.php"

        return url
    
    async def has_requested_today(self, user_id):
        """检查用户今天是否已经请求过"""
        # 使用配置的时区获取今天的日期
        tz = pytz.timezone(self.time_zone)
        today = datetime.now(tz).strftime("%Y-%m-%d")
        
        try:
            # 使用插件数据持久化功能获取用户请求记录
            storage_key = f"user_request_{user_id}"
            stored_date_bytes = await self.plugin.get_plugin_storage(storage_key)
            
            if stored_date_bytes:
                # 将字节转换回字符串
                stored_date = stored_date_bytes.decode('utf-8')
                # 检查存储的日期是否为今天
                return stored_date == today
            
        except Exception as e:
            print(f"检查请求记录失败: {e}")
        
        return False
    
    async def record_request(self, user_id):
        """记录用户请求"""
        # 使用配置的时区获取今天的日期
        tz = pytz.timezone(self.time_zone)
        today = datetime.now(tz).strftime("%Y-%m-%d")
        
        try:
            # 使用插件数据持久化功能保存用户请求记录
            storage_key = f"user_request_{user_id}"
            # 将日期字符串转换为字节
            today_bytes = today.encode('utf-8')
            await self.plugin.set_plugin_storage(storage_key, today_bytes)
                
        except Exception as e:
            print(f"记录请求失败: {e}")